package dns

import (
	"os"
	"strings"
	"testing"
)

// --- renderDnsmasqConfig ---

func TestRenderDnsmasqConfig_multiTLD(t *testing.T) {
	got := renderDnsmasqConfig([]string{"test", "local"}, []string{"1.1.1.1"}, "127.0.0.1", "::1")

	for _, want := range []string{
		"port=5300",
		"no-resolv",
		"server=1.1.1.1",
		"address=/.test/127.0.0.1",
		"address=/.test/::1",
		"address=/.local/127.0.0.1",
		"address=/.local/::1",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("renderDnsmasqConfig() missing %q in:\n%s", want, got)
		}
	}
}

func TestRenderDnsmasqConfig_noUpstreamNoV6(t *testing.T) {
	got := renderDnsmasqConfig([]string{"test"}, nil, "127.0.0.1", "")

	if strings.Contains(got, "no-resolv") {
		t.Errorf("expected no-resolv omitted when there are no upstreams:\n%s", got)
	}
	if strings.Contains(got, "::1") || strings.Contains(got, "address=/.test/::") {
		t.Errorf("expected no AAAA record when v6Target is empty:\n%s", got)
	}
	if !strings.Contains(got, "address=/.test/127.0.0.1") {
		t.Errorf("expected the v4 record:\n%s", got)
	}
}

// --- parseNameservers ---

func TestParseNameservers_realServers(t *testing.T) {
	f := writeTempFile(t, `
# Generated by NetworkManager
nameserver 192.168.1.1
nameserver 8.8.8.8
`)
	got := parseNameservers(f)
	want := []string{"192.168.1.1", "8.8.8.8"}
	assertSliceEqual(t, got, want)
}

func TestParseNameservers_skipsLoopback(t *testing.T) {
	f := writeTempFile(t, `
nameserver 127.0.0.1
nameserver 127.0.0.53
nameserver ::1
nameserver 10.0.0.1
`)
	got := parseNameservers(f)
	want := []string{"10.0.0.1"}
	assertSliceEqual(t, got, want)
}

func TestParseNameservers_onlyLoopback(t *testing.T) {
	f := writeTempFile(t, "nameserver 127.0.0.53\n")
	got := parseNameservers(f)
	if len(got) != 0 {
		t.Errorf("expected empty, got %v", got)
	}
}

func TestParseNameservers_missingFile(t *testing.T) {
	got := parseNameservers("/nonexistent/resolv.conf")
	if got != nil {
		t.Errorf("expected nil for missing file, got %v", got)
	}
}

func TestParseNameservers_skipsZonedLinkLocal(t *testing.T) {
	f := writeTempFile(t, `
nameserver fe80::46d4:53ff:fe3f:a9a7%18
nameserver fe80::1%eth0
nameserver 8.8.8.8
`)
	got := parseNameservers(f)
	want := []string{"8.8.8.8"}
	assertSliceEqual(t, got, want)
}

func TestSanitizeDNSIP(t *testing.T) {
	cases := []struct {
		in, want string
	}{
		{"8.8.8.8", "8.8.8.8"},
		{"  1.1.1.1  ", "1.1.1.1"},
		{"169.254.1.1", "169.254.1.1"},
		{"2606:4700:4700::1111", "2606:4700:4700::1111"},
		{"127.0.0.1", ""},
		{"127.0.0.53", ""},
		{"::1", ""},
		{"0.0.0.0", ""},
		{"", ""},
		{"--", ""},
		{"not-an-ip", ""},
		{"fe80::46d4:53ff:fe3f:a9a7%18", ""},
		{"fe80::1%eth0", ""},
	}
	for _, c := range cases {
		if got := sanitizeDNSIP(c.in); got != c.want {
			t.Errorf("sanitizeDNSIP(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}

func TestParseNameservers_commentsIgnored(t *testing.T) {
	f := writeTempFile(t, `
# This is a comment
; another comment
search example.com
nameserver 1.1.1.1
`)
	got := parseNameservers(f)
	want := []string{"1.1.1.1"}
	assertSliceEqual(t, got, want)
}

// --- isFileContent ---

func TestIsFileContent_match(t *testing.T) {
	f := writeTempFile(t, "hello world")
	if !isFileContent(f, []byte("hello world")) {
		t.Error("expected match")
	}
}

func TestIsFileContent_mismatch(t *testing.T) {
	f := writeTempFile(t, "hello world")
	if isFileContent(f, []byte("different")) {
		t.Error("expected mismatch")
	}
}

func TestIsFileContent_missingFile(t *testing.T) {
	if isFileContent("/nonexistent/file", []byte("x")) {
		t.Error("expected false for missing file")
	}
}

// --- helpers ---

func writeTempFile(t *testing.T, content string) string {
	t.Helper()
	f, err := os.CreateTemp(t.TempDir(), "resolv-*.conf")
	if err != nil {
		t.Fatal(err)
	}
	f.WriteString(content)
	f.Close()
	return f.Name()
}

func assertSliceEqual(t *testing.T, got, want []string) {
	t.Helper()
	if len(got) != len(want) {
		t.Errorf("got %v, want %v", got, want)
		return
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("index %d: got %q, want %q", i, got[i], want[i])
		}
	}
}

func assertContains(t *testing.T, s, substr string) {
	t.Helper()
	if !strings.Contains(s, substr) {
		t.Errorf("expected %q to contain %q", s, substr)
	}
}
