package dns

import (
	"os"
	"path/filepath"
	"testing"
)

func withWSLSeams(t *testing.T, onWSL, resolved bool, resolvConf string) {
	t.Helper()
	origWSL, origPath, origResolved := isWSL, resolvConfPath, resolvedIsRunning
	t.Cleanup(func() { isWSL, resolvConfPath, resolvedIsRunning = origWSL, origPath, origResolved })
	p := filepath.Join(t.TempDir(), "resolv.conf")
	if err := os.WriteFile(p, []byte(resolvConf), 0o644); err != nil {
		t.Fatal(err)
	}
	isWSL = func() bool { return onWSL }
	resolvedIsRunning = func() bool { return resolved }
	resolvConfPath = p
}

const wslResolvConf = "# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:\n# [network]\n# generateResolvConf = false\nnameserver 10.255.255.254\n"

func TestWSLHandoverNameservers_WSLGeneratedFile(t *testing.T) {
	withWSLSeams(t, true, true, wslResolvConf)
	got := wslHandoverNameservers()
	if len(got) != 1 || got[0] != "10.255.255.254" {
		t.Errorf("got %v, want [10.255.255.254]", got)
	}
}

func TestWSLHandoverNameservers_NothingToDo(t *testing.T) {
	cases := []struct {
		name           string
		onWSL, running bool
		conf           string
	}{
		{"not WSL", false, true, wslResolvConf},
		{"resolved not running", true, false, wslResolvConf},
		{"already handed over", true, true, "nameserver 127.0.0.53\n"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			withWSLSeams(t, c.onWSL, c.running, c.conf)
			if got := wslHandoverNameservers(); got != nil {
				t.Errorf("got %v, want nil", got)
			}
		})
	}
}
