package services

import (
	"os"
	"path/filepath"
	"testing"
)

func TestWorkerGuardWorkingDir_hostMode(t *testing.T) {
	script := `#!/bin/sh
# Generated by lerd. Host-mode worker guard.
export PATH="/Users/u/.local/share/lerd/bin:/opt/homebrew/bin:$PATH"
export FORCE_COLOR=1
cd '/Users/u/Projects/app-feat-login' || exit 1
exec /bin/sh -c 'npm run dev'
`
	if got := WorkerGuardWorkingDir(script); got != "/Users/u/Projects/app-feat-login" {
		t.Errorf("WorkerGuardWorkingDir = %q, want the cd target", got)
	}
}

func TestWorkerGuardWorkingDir_hostModeEscapedQuote(t *testing.T) {
	// The builder escapes an embedded single quote as '"'"'.
	script := "cd '/Users/u/it'\"'\"'s/app' || exit 1\nexec /bin/sh -c 'npm run dev'\n"
	if got := WorkerGuardWorkingDir(script); got != "/Users/u/it's/app" {
		t.Errorf("WorkerGuardWorkingDir = %q, want the unescaped path", got)
	}
}

func TestWorkerGuardWorkingDir_execMode(t *testing.T) {
	script := `#!/bin/sh
if [ -f '/run/w.pid' ] && kill -0 "$(cat '/run/w.pid' 2>/dev/null)" 2>/dev/null; then
  exit 0
fi
/opt/homebrew/bin/podman exec lerd-php83-fpm sh -c 'm() { for p in $(pgrep -f -- '"'"'artisan queue:work'"'"'); do [ "$(readlink /proc/$p/cwd 2>/dev/null)" = '"'"'/Users/u/Projects/app'"'"' ] && echo "$p"; done; }' >/dev/null 2>&1 || true
echo $$ > '/run/w.pid'
trap 'rm -f '/run/w.pid'' EXIT
exec /opt/homebrew/bin/podman exec -w /Users/u/Projects/app-feat-login --env=FORCE_COLOR=1 lerd-php83-fpm php artisan queue:work
`
	if got := WorkerGuardWorkingDir(script); got != "/Users/u/Projects/app-feat-login" {
		t.Errorf("WorkerGuardWorkingDir = %q, want the -w target of the exec line", got)
	}
}

// A guard whose exec line carries no -w pins no directory. The reap line names
// the site path inside a quoted snippet, and must not be read as one.
func TestWorkerGuardWorkingDir_noDirectory(t *testing.T) {
	script := `#!/bin/sh
/opt/homebrew/bin/podman exec lerd-php83-fpm sh -c 'readlink /proc/$p/cwd = '"'"'/Users/u/Projects/app'"'"'' >/dev/null 2>&1 || true
exec /opt/homebrew/bin/podman exec lerd-php83-fpm php artisan queue:work
`
	if got := WorkerGuardWorkingDir(script); got != "" {
		t.Errorf("WorkerGuardWorkingDir = %q, want empty for a guard that pins no directory", got)
	}
}

func TestWorkerWorkingDirs_readsGuardScripts(t *testing.T) {
	tmp := t.TempDir()
	t.Setenv("XDG_DATA_HOME", tmp)
	dir := filepath.Join(tmp, "lerd", "run", "workers")
	if err := os.MkdirAll(dir, 0755); err != nil {
		t.Fatal(err)
	}
	write := func(name, body string) {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0755); err != nil {
			t.Fatal(err)
		}
	}
	write("lerd-vite-app-feat-login.sh", "cd '/Users/u/Projects/app-feat-login' || exit 1\nexec /bin/sh -c 'npm run dev'\n")
	write("lerd-queue-app.sh", "exec /opt/homebrew/bin/podman exec -w /Users/u/Projects/app lerd-php83-fpm php artisan queue:work\n")
	write("lerd-queue-app.pid", "1234\n")

	got := WorkerWorkingDirs()
	for unit, want := range map[string]string{
		"lerd-vite-app-feat-login":         "/Users/u/Projects/app-feat-login",
		"lerd-vite-app-feat-login.service": "/Users/u/Projects/app-feat-login",
		"lerd-queue-app":                   "/Users/u/Projects/app",
		"lerd-queue-app.service":           "/Users/u/Projects/app",
	} {
		if got[unit] != want {
			t.Errorf("WorkerWorkingDirs()[%q] = %q, want %q", unit, got[unit], want)
		}
	}
	if _, ok := got["lerd-queue-app.pid"]; ok {
		t.Error("WorkerWorkingDirs included a non-script sidecar")
	}
}

func TestWorkerWorkingDirs_noWorkersDir(t *testing.T) {
	t.Setenv("XDG_DATA_HOME", t.TempDir())
	if got := WorkerWorkingDirs(); len(got) != 0 {
		t.Errorf("WorkerWorkingDirs = %v, want empty when nothing is on disk", got)
	}
}
