package config

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
)

// A dev server advertises its own address, so everything it serves points at a
// port only this machine can reach. Putting it behind the site's own domain is
// a property of the tool, not of the framework running it, so what each tool
// needs is described here rather than restated in every framework definition.

// DevServerTool describes one supported dev server.
type DevServerTool struct {
	Name string
	// Base is the URL prefix every dev URL lives under, so a single nginx
	// location carries the assets and the hot-reload socket alike.
	Base string
	// ProjectConfig lists candidate config filenames, first match wins.
	ProjectConfig []string
	// WrapperPath is where the generated config goes, relative to the site.
	WrapperPath string
	// Args is appended to the worker command, with {config} and {port} filled in.
	Args string
	// Wrapper is the generated config, taking the import path, base, origin,
	// allowed hosts and the origins allowed to fetch from the server. Every
	// placeholder is filled with an encoded JavaScript literal, so none of them
	// carries its own quotes.
	Wrapper     string
	DefaultPort int
}

var devServerTools = []DevServerTool{{
	Name:          "vite",
	Base:          "/@lerd-vite/",
	ProjectConfig: []string{"vite.config.js", "vite.config.ts", "vite.config.mjs", "vite.config.mts"},
	WrapperPath:   "node_modules/.lerd/vite.config.mjs",
	Args:          "-- --config {config} --port {port} --strictPort",
	DefaultPort:   5173,
	Wrapper: `// Generated by lerd, rewritten on every start. Not committed, not user-editable.
// Wraps the project's own config so the dev server answers on the site's domain.
import { mergeConfig } from 'vite';
import projectConfig from %s;

const lerd = {
    base: %s,
    server: {
        host: true,
        origin: %s,
        allowedHosts: %s,
        // Naming an origin makes some framework plugins treat it as the whole
        // CORS allowlist, so a page on any other domain of the site would be
        // refused the assets it just asked for. Declare them all.
        cors: { origin: %s },
    },
};

export default async (env) => {
    const resolved = await (typeof projectConfig === 'function' ? projectConfig(env) : projectConfig);
    return env.command === 'serve' ? mergeConfig(resolved, lerd) : resolved;
};
`,
}}

// DevServerToolInstalled returns the dev server the project has installed, or
// nil. Used where only the tool's shape matters, such as rendering the vhost.
func DevServerToolInstalled(sitePath string) *DevServerTool {
	for i := range devServerTools {
		t := &devServerTools[i]
		if _, err := os.Stat(filepath.Join(sitePath, "node_modules", t.Name)); err == nil {
			return t
		}
	}
	return nil
}

// DevServerToolFor returns the dev server a worker command actually starts, or
// nil when the command runs something else. A command that only reaches the
// tool through a runner (concurrently and friends) is deliberately not matched:
// the flags lerd appends would land on the wrong process.
func DevServerToolFor(sitePath, command string) *DevServerTool {
	t := DevServerToolInstalled(sitePath)
	if t == nil {
		return nil
	}
	if !commandInvokes(sitePath, command, t.Name) {
		return nil
	}
	return t
}

// commandInvokes reports whether command starts the named tool directly,
// following one level of package-manager script indirection.
func commandInvokes(sitePath, command, tool string) bool {
	if invokesDirectly(command, tool) {
		return true
	}
	script := packageScript(sitePath, scriptNameFrom(command))
	return script != "" && invokesDirectly(script, tool)
}

// scriptNameFrom returns the script a "<pm> run <name>" command would run.
func scriptNameFrom(command string) string {
	fields := strings.Fields(command)
	if len(fields) < 3 {
		return ""
	}
	switch filepath.Base(fields[0]) {
	case "npm", "pnpm", "yarn", "bun":
	default:
		return ""
	}
	if fields[1] != "run" {
		return ""
	}
	return fields[2]
}

func packageScript(sitePath, name string) string {
	if name == "" {
		return ""
	}
	data, err := os.ReadFile(filepath.Join(sitePath, "package.json"))
	if err != nil {
		return ""
	}
	var pkg struct {
		Scripts map[string]string `json:"scripts"`
	}
	if json.Unmarshal(data, &pkg) != nil {
		return ""
	}
	return pkg.Scripts[name]
}

// invokesDirectly reports whether the tool is the first thing the command runs,
// rather than something a runner reaches later in the line.
func invokesDirectly(command, tool string) bool {
	fields := strings.Fields(command)
	if len(fields) == 0 {
		return false
	}
	first := fields[0]
	if first == "npx" && len(fields) > 1 {
		first = fields[1]
	}
	return filepath.Base(first) == tool
}
