package podman

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/geodro/lerd/internal/config"
)

// odbcInstHeader opens the generated driver registry. The file is rewritten on
// every php:odbc change, so it says so rather than inviting an edit that the
// next registration would silently drop.
const odbcInstHeader = "; Generated by lerd php:odbc. Rewritten on every change.\n" +
	"; Register a driver with `lerd php:odbc add <name> <path-to-driver.so>`.\n"

// validODBCName matches a driver name safe to write as an odbcinst section and
// to type inside a DSN's Driver={...}.
var validODBCName = regexp.MustCompile(`^[A-Za-z0-9._ -]+$`)

// ValidODBCDriverName reports whether name can be used as a driver name.
func ValidODBCDriverName(name string) bool {
	return validODBCName.MatchString(strings.TrimSpace(name))
}

// RenderOdbcInst renders the unixODBC driver registry. With no drivers
// registered it is the header alone, which keeps the bind-mount source a
// regular file so podman never puts a directory at /etc/odbcinst.ini.
func RenderOdbcInst(drivers []config.ODBCDriver) string {
	var b strings.Builder
	b.WriteString(odbcInstHeader)
	for _, d := range drivers {
		name := strings.TrimSpace(d.Name)
		if name == "" || !ValidODBCDriverName(name) {
			continue
		}
		fmt.Fprintf(&b, "\n[%s]\n", name)
		if desc := strings.TrimSpace(d.Description); desc != "" {
			fmt.Fprintf(&b, "Description = %s\n", desc)
		}
		fmt.Fprintf(&b, "Driver = %s\n", strings.TrimSpace(d.Driver))
	}
	return b.String()
}

// EnsureOdbcInst writes the driver registry from the saved config. Called from
// every quadlet write, since the file is a bind-mount source: podman would
// auto-create a directory in its place and the container's driver manager would
// then read nothing.
func EnsureOdbcInst() error {
	path := config.OdbcInstFile()
	if info, err := os.Stat(path); err == nil && info.IsDir() {
		if rmErr := os.RemoveAll(path); rmErr != nil {
			return fmt.Errorf("removing stale odbcinst directory: %w", rmErr)
		}
	}
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	var drivers []config.ODBCDriver
	if cfg, err := config.LoadGlobal(); err == nil {
		drivers = cfg.GetODBCDrivers()
	}
	return os.WriteFile(path, []byte(RenderOdbcInst(drivers)), 0644)
}

// odbcInstMountLine returns the Volume= line mounting lerd's driver registry,
// or "" when nothing is registered. Left out rather than mounted empty: a
// per-site image that writes its own /etc/odbcinst.ini would otherwise have it
// shadowed by a registry with no drivers in it, and lose every driver it has.
func odbcInstMountLine() string {
	cfg, err := config.LoadGlobal()
	if err != nil || len(cfg.GetODBCDrivers()) == 0 {
		return ""
	}
	return "Volume=" + config.OdbcInstFile() + ":/etc/odbcinst.ini:ro"
}

// ODBCDriverDirs returns the directories holding registered drivers, so a
// container that does not already mount the whole home can still reach them.
// Missing and unmountable paths are dropped: a Volume= line for a path that is
// not there makes podman refuse to start the container.
func ODBCDriverDirs() []string {
	cfg, err := config.LoadGlobal()
	if err != nil {
		return nil
	}
	seen := map[string]bool{}
	var dirs []string
	for _, d := range cfg.GetODBCDrivers() {
		dir := filepath.Dir(strings.TrimSpace(d.Driver))
		if !bindMountable(dir) || seen[dir] {
			continue
		}
		if _, statErr := os.Stat(dir); statErr != nil {
			continue
		}
		seen[dir] = true
		dirs = append(dirs, dir)
	}
	return dirs
}

// ODBCDriverStatus is what the image says about a registered driver: whether
// the container can see the file, whether the driver manager lists it, and what
// the loader cannot satisfy — libraries that are absent, and symbols that are
// missing from the ones that are there.
type ODBCDriverStatus struct {
	Found      bool
	Registered bool
	Unresolved []string
	Symbols    []string
}

// Loadable reports whether the driver would actually open. unixODBC answers a
// driver it cannot dlopen with "file not found" whatever the real reason, so
// both loader failures have to be caught here or a registration reads as fine
// and fails later as an empty connection error.
func (s ODBCDriverStatus) Loadable() bool {
	return s.Found && len(s.Unresolved) == 0 && len(s.Symbols) == 0
}

// unresolvedLib matches musl's loader complaint for a library it cannot find,
// which is how a glibc-built driver reports what gcompat did not cover.
var unresolvedLib = regexp.MustCompile(`Error loading shared library ([^:]+):`)

// unresolvedSymbol matches the other half of the same story: every library
// resolved, but one of them is musl standing in for glibc and does not carry
// the symbol. A HANA driver lands here on qfcvt_r and friends.
var unresolvedSymbol = regexp.MustCompile(`Error relocating [^:]+: ([A-Za-z0-9_]+): symbol not found`)

// parseODBCProbe reads the in-container probe output. Split from the podman
// call so the parsing is testable against real driver output.
func parseODBCProbe(text, driverName string) ODBCDriverStatus {
	status := ODBCDriverStatus{
		Found:      strings.Contains(text, "LERD_FOUND"),
		Registered: strings.Contains(text, "["+driverName+"]"),
	}
	for _, m := range unresolvedLib.FindAllStringSubmatch(text, -1) {
		status.Unresolved = append(status.Unresolved, strings.TrimSpace(m[1]))
	}
	seen := map[string]bool{}
	for _, m := range unresolvedSymbol.FindAllStringSubmatch(text, -1) {
		sym := strings.TrimSpace(m[1])
		if seen[sym] {
			continue
		}
		seen[sym] = true
		status.Symbols = append(status.Symbols, sym)
	}
	return status
}

// InspectODBCDriver reports what version's image makes of the driver registered
// under name, by reading it from inside that image with the same registry and
// mounts a container gets. A driver the manager does not list, or one missing a
// library, is the difference between a working DSN and a connection error with
// nothing useful in it.
func InspectODBCDriver(version string, d config.ODBCDriver) (ODBCDriverStatus, error) {
	var status ODBCDriverStatus
	args := []string{"run", "--rm", "-v", config.OdbcInstFile() + ":/etc/odbcinst.ini:ro"}
	if dir := filepath.Dir(d.Driver); bindMountable(dir) {
		args = append(args, "-v", dir+":"+dir+":ro")
	}
	script := "test -f '" + d.Driver + "' && echo LERD_FOUND; odbcinst -q -d 2>/dev/null; ldd '" + d.Driver + "' 2>&1"
	args = append(args, FPMImageName(version), "sh", "-c", script)

	out, err := execCommand(PodmanBin(), args...).CombinedOutput()
	if err != nil && len(out) == 0 {
		return status, fmt.Errorf("inspecting %s in the PHP %s image: %w", d.Name, version, err)
	}
	return parseODBCProbe(string(out), d.Name), nil
}
